### ISSUE TITLE
Ongoing Questions

### ISSUE THREAD

**Issue by hollenberry** [githubschool/apr-23#2]
There are many ways and places to ask questions. 
- Please feel free to interrupt me during class with questions on your microphone or in chat. 
- Post questions in this issue.
- Email me if you'd like to keep questions private (hollenberry@github.com)

**Comment by githubteacher** [comment]
Can you apply local config settings for individual repositories?

**Comment by githubteacher** [comment]
How do we squelch the "LF will be replaced with CRLF" warning prompt in CLI? 

- git config --global core.safecrlf false

**Comment by githubteacher** [comment]
Can JIRA be accessed (using the plug-in) in the same way that issues/PRs are linked? 

- No, not in real time.

**Comment by githubteacher** [comment]
Can I use git log or a command to find the starting point of a branch that a commit is on? 
- git cherry -v change-speed master

**Comment by githubteacher** [comment]
What's the difference between a Member and an Outside Collaborator?
